name: Package release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Installing dependencies
      run: yarn install
    - name: Packaging
      run: vsce package
    - run: ls
    - name: Action Release
      uses: yakuhzi/action-release@v1.2.0
      with:
        file: bitdev-vscode-extension.vsix
  
