name: Package release on github

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: stable
    - name: Installing dependencies
      run: yarn install
    - name: Packaging
      run: yarn package
    - run: ls
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: bitdev.vsix
        GITHUB_TOKEN: ${{ secrets.GITHUB_RELEASE }}
  
